language: php

php:
  - 7.2

#matrix:
#  fast_finish: true
#  allow_failures:
#    - php: 7.2

before_script:
  - composer install --prefer-dist --dev

script:
  - vendor/bin/simple-phpunit
  - vendor/bin/phpcs --standard=PSR2 -n bin/ config/ public/ src/ tests/
