language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - composer install --prefer-dist --dev

script:
  - vendor/bin/simple-phpunit
  - vendor/bin/phpcs --standard=PSR2 -n bin/ config/ public/ src/ tests/
