name: phpunit
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1

      - name: PHPUnit
        uses: chindit/actions-phpunit-symfony@master
